version: "3.9"
services:
  client:
    stdin_open: true
    build: ./client
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules 
      - ./client/src:/app/src
    environment: 
      - CHOKIDAR_USEPOLLING=true
    container_name: client
  api:
    build: ./api
    restart: unless-stopped
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    stdin_open: true
    volumes:
      - ./api/src:/api/src
      - ./api/nodemon.json:/api/nodemon.json
    container_name: api
    expose:
      - 4000
    ports:
      - "4000:4000"
    depends_on: 
      - mongo
    command: npm run dev
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./db/data/db:/data/db
    logging:
      driver: "none"